import dotenv from "dotenv";
dotenv.config();

export const BASE_API_URL = process.env.BASE_API_URL || "API_URL";
export const RAPID_API_KEY = process.env.RAPID_API_KEY || "API_KEY";
export const RAPID_API_HOST = process.env.RAPID_API_HOST || "API_HOST";
export const BOT_TOKEN = process.env.BOT_TOKEN || "EMPTY_TOKEN";
export const COMMANDS = [
  { command: "/start", description: "Начальное приветсвие" },
  { command: "/languages", description: "Получить список языков" },
  { command: "/help", description: "Узнать как пользоватся ботом" },
];
export const VALID_LANGUAGES = [
  "Код языка: af | Язык: Afrikaans / Afrikaans",
  "Код языка: am | Язык: Amharic / አማርኛ",
  "Код языка: ar | Язык: Arabic / العربية",
  "Код языка: as | Язык: Assamese / অসমীয়া",
  "Код языка: az | Язык: Azerbaijani / Azərbaycan",
  "Код языка: ba | Язык: Bashkir / Bashkir",
  "Код языка: bg | Язык: Bulgarian / Български",
  "Код языка: bn | Язык: Bangla / বাংলা",
  "Код языка: bo | Язык: Tibetan / བོད་སྐད་",
  "Код языка: bs | Язык: Bosnian / Bosnian",
  "Код языка: ca | Язык: Catalan / Català",
  "Код языка: cs | Язык: Czech / Čeština",
  "Код языка: cy | Язык: Welsh / Cymraeg",
  "Код языка: da | Язык: Danish / Dansk",
  "Код языка: de | Язык: German / Deutsch",
  "Код языка: dv | Язык: Divehi / ދިވެހިބަސް",
  "Код языка: el | Язык: Greek / Ελληνικά",
  "Код языка: en | Язык: English / English",
  "Код языка: es | Язык: Spanish / Español",
  "Код языка: et | Язык: Estonian / Eesti",
  "Код языка: eu | Язык: Basque / Euskara",
  "Код языка: fa | Язык: Persian / فارسی",
  "Код языка: fi | Язык: Finnish / Suomi",
  "Код языка: fil | Язык: Filipino / Filipino",
  "Код языка: fj | Язык: Fijian / Na Vosa Vakaviti",
  "Код языка: fo | Язык: Faroese / Føroyskt",
  "Код языка: fr | Язык: French / Français",
  "Код языка: fr-CA | Язык: French (Canada) / Français (Canada)",
  "Код языка: ga | Язык: Irish / Gaeilge",
  "Код языка: gl | Язык: Galician / Galego",
  "Код языка: gu | Язык: Gujarati / ગુજરાતી",
  "Код языка: he | Язык: Hebrew / עברית",
  "Код языка: hi | Язык: Hindi / हिन्दी",
  "Код языка: hr | Язык: Croatian / Hrvatski",
  "Код языка: hsb | Язык: Upper Sorbian / Hornjoserbšćina",
  "Код языка: ht | Язык: Haitian Creole / Haitian Creole",
  "Код языка: hu | Язык: Hungarian / Magyar",
  "Код языка: hy | Язык: Armenian / Հայերեն",
  "Код языка: id | Язык: Indonesian / Indonesia",
  "Код языка: ikt | Язык: Inuinnaqtun / Inuinnaqtun",
  "Код языка: is | Язык: Icelandic / Íslenska",
  "Код языка: it | Язык: Italian / Italiano",
  "Код языка: iu | Язык: Inuktitut / ᐃᓄᒃᑎᑐᑦ",
  "Код языка: iu-Latn | Язык: Inuktitut (Latin) / Inuktitut (Latin)",
  "Код языка: ja | Язык: Japanese / 日本語",
  "Код языка: ka | Язык: Georgian / ქართული",
  "Код языка: kk | Язык: Kazakh / Қазақ Тілі",
  "Код языка: km | Язык: Khmer / ខ្មែរ",
  "Код языка: kmr | Язык: Kurdish (Northern) / Kurdî (Bakur)",
  "Код языка: kn | Язык: Kannada / ಕನ್ನಡ",
  "Код языка: ko | Язык: Korean / 한국어",
  "Код языка: ku | Язык: Kurdish (Central) / Kurdî (Navîn)",
  "Код языка: ky | Язык: Kyrgyz / Кыргызча",
  "Код языка: lo | Язык: Lao / ລາວ",
  "Код языка: lt | Язык: Lithuanian / Lietuvių",
  "Код языка: lv | Язык: Latvian / Latviešu",
  "Код языка: lzh | Язык: Chinese (Literary) / 中文 (文言文)",
  "Код языка: mg | Язык: Malagasy / Malagasy",
  "Код языка: mi | Язык: Māori / Te Reo Māori",
  "Код языка: mk | Язык: Macedonian / Македонски",
  "Код языка: ml | Язык: Malayalam / മലയാളം",
  "Код языка: mn-Cyrl | Язык: Mongolian (Cyrillic) / Mongolian (Cyrillic)",
  "Код языка: mn-Mong | Язык: Mongolian (Traditional) / ᠮᠣᠩᠭᠣᠯ ᠬᠡᠯᠡ",
  "Код языка: mr | Язык: Marathi / मराठी",
  "Код языка: ms | Язык: Malay / Melayu",
  "Код языка: mt | Язык: Maltese / Malti",
  "Код языка: mww | Язык: Hmong Daw / Hmong Daw",
  "Код языка: my | Язык: Myanmar (Burmese) / မြန်မာ",
  "Код языка: nb | Язык: Norwegian / Norsk Bokmål",
  "Код языка: ne | Язык: Nepali / नेपाली",
  "Код языка: nl | Язык: Dutch / Nederlands",
  "Код языка: or | Язык: Odia / ଓଡ଼ିଆ",
  "Код языка: otq | Язык: Querétaro Otomi / Hñähñu",
  "Код языка: pa | Язык: Punjabi / ਪੰਜਾਬੀ",
  "Код языка: pl | Язык: Polish / Polski",
  "Код языка: prs | Язык: Dari / دری",
  "Код языка: ps | Язык: Pashto / پښتو",
  "Код языка: pt | Язык: Portuguese (Brazil) / Português (Brasil)",
  "Код языка: pt-PT | Язык: Portuguese (Portugal) / Português (Portugal)",
  "Код языка: ro | Язык: Romanian / Română",
  "Код языка: ru | Язык: Russian / Русский",
  "Код языка: sk | Язык: Slovak / Slovenčina",
  "Код языка: sl | Язык: Slovenian / Slovenščina",
  "Код языка: sm | Язык: Samoan / Gagana Sāmoa",
  "Код языка: so | Язык: Somali / Soomaali",
  "Код языка: sq | Язык: Albanian / Shqip",
  "Код языка: sr-Cyrl | Язык: Serbian (Cyrillic) / Српски (ћирилица)",
  "Код языка: sr-Latn | Язык: Serbian (Latin) / Srpski (latinica)",
  "Код языка: sv | Язык: Swedish / Svenska",
  "Код языка: sw | Язык: Swahili / Kiswahili",
  "Код языка: ta | Язык: Tamil / தமிழ்",
  "Код языка: te | Язык: Telugu / తెలుగు",
  "Код языка: th | Язык: Thai / ไทย",
  "Код языка: ti | Язык: Tigrinya / ትግር",
  "Код языка: tk | Язык: Turkmen / Türkmen Dili",
  "Код языка: tlh-Latn | Язык: Klingon (Latin) / Klingon (Latin)",
  "Код языка: tlh-Piqd | Язык: Klingon (pIqaD) / Klingon (pIqaD)",
  "Код языка: to | Язык: Tongan / Lea Fakatonga",
  "Код языка: tr | Язык: Turkish / Türkçe",
  "Код языка: tt | Язык: Tatar / Татар",
  "Код языка: ty | Язык: Tahitian / Reo Tahiti",
  "Код языка: ug | Язык: Uyghur / ئۇيغۇرچە",
  "Код языка: uk | Язык: Ukrainian / Українська",
  "Код языка: ur | Язык: Urdu / اردو",
  "Код языка: uz | Язык: Uzbek (Latin) / Uzbek (Latin)",
  "Код языка: vi | Язык: Vietnamese / Tiếng Việt",
  "Код языка: yua | Язык: Yucatec Maya / Yucatec Maya",
  "Код языка: yue | Язык: Cantonese (Traditional) / 粵語 (繁體)",
  "Код языка: zh-Hans | Язык: Chinese Simplified / 中文 (简体)",
  "Код языка: zh-Hant | Язык: Chinese Traditional / 繁體中文 (繁體)",
  "Код языка: zu | Язык: Zulu / Isi-Zulu",
];
