export const commands = [
  { command: "/start", description: "Начальное приветсвие" },
  { command: "/languages", description: "Получить список языков" },
];

export const languagesPart1 = [
  "Code: af Language: Afrikaans / Afrikaans",
  "Code: am Language: Amharic / አማርኛ",
  "Code: ar Language: Arabic / العربية",
  "Code: as Language: Assamese / অসমীয়া",
  "Code: az Language: Azerbaijani / Azərbaycan",
  "Code: ba Language: Bashkir / Bashkir",
  "Code: bg Language: Bulgarian / Български",
  "Code: bn Language: Bangla / বাংলা",
  "Code: bo Language: Tibetan / བོད་སྐད་",
  "Code: bs Language: Bosnian / Bosnian",
  "Code: ca Language: Catalan / Català",
  "Code: cs Language: Czech / Čeština",
  "Code: cy Language: Welsh / Cymraeg",
  "Code: da Language: Danish / Dansk",
  "Code: de Language: German / Deutsch",
  "Code: dv Language: Divehi / ދިވެހިބަސް",
  "Code: el Language: Greek / Ελληνικά",
  "Code: en Language: English / English",
  "Code: es Language: Spanish / Español",
  "Code: et Language: Estonian / Eesti",
  "Code: eu Language: Basque / Euskara",
  "Code: fa Language: Persian / فارسی",
  "Code: fi Language: Finnish / Suomi",
  "Code: fil Language: Filipino / Filipino",
  "Code: fj Language: Fijian / Na Vosa Vakaviti",
  "Code: fo Language: Faroese / Føroyskt",
  "Code: fr Language: French / Français",
  "Code: fr-CA Language: French (Canada) / Français (Canada)",
  "Code: ga Language: Irish / Gaeilge",
  "Code: gl Language: Galician / Galego",
  "Code: gu Language: Gujarati / ગુજરાતી",
  "Code: he Language: Hebrew / עברית",
  "Code: hi Language: Hindi / हिन्दी",
  "Code: hr Language: Croatian / Hrvatski",
  "Code: hsb Language: Upper Sorbian / Hornjoserbšćina",
  "Code: ht Language: Haitian Creole / Haitian Creole",
  "Code: hu Language: Hungarian / Magyar",
  "Code: hy Language: Armenian / Հայերեն",
  "Code: id Language: Indonesian / Indonesia",
  "Code: ikt Language: Inuinnaqtun / Inuinnaqtun",
  "Code: is Language: Icelandic / Íslenska",
  "Code: it Language: Italian / Italiano",
  "Code: iu Language: Inuktitut / ᐃᓄᒃᑎᑐᑦ",
  "Code: iu-Latn Language: Inuktitut (Latin) / Inuktitut (Latin)",
  "Code: ja Language: Japanese / 日本語",
  "Code: ka Language: Georgian / ქართული",
  "Code: kk Language: Kazakh / Қазақ Тілі",
  "Code: km Language: Khmer / ខ្មែរ",
  "Code: kmr Language: Kurdish (Northern) / Kurdî (Bakur)",
  "Code: kn Language: Kannada / ಕನ್ನಡ",
  "Code: ko Language: Korean / 한국어",
  "Code: ku Language: Kurdish (Central) / Kurdî (Navîn)",
  "Code: ky Language: Kyrgyz / Кыргызча",
  "Code: lo Language: Lao / ລາວ",
  "Code: lt Language: Lithuanian / Lietuvių",
  "Code: lv Language: Latvian / Latviešu",
  "Code: lzh Language: Chinese (Literary) / 中文 (文言文)",
  "Code: mg Language: Malagasy / Malagasy",
  "Code: mi Language: Māori / Te Reo Māori",
  "Code: mk Language: Macedonian / Македонски",
  "Code: ml Language: Malayalam / മലയാളം",
  "Code: mn-Cyrl Language: Mongolian (Cyrillic) / Mongolian (Cyrillic)",
  "Code: mn-Mong Language: Mongolian (Traditional) / ᠮᠣᠩᠭᠣᠯ ᠬᠡᠯᠡ",
  "Code: mr Language: Marathi / मराठी",
];

export const languagesPart2 = [
  "Code: ms Language: Malay / Melayu",
  "Code: mt Language: Maltese / Malti",
  "Code: mww Language: Hmong Daw / Hmong Daw",
  "Code: my Language: Myanmar (Burmese) / မြန်မာ",
  "Code: nb Language: Norwegian / Norsk Bokmål",
  "Code: ne Language: Nepali / नेपाली",
  "Code: nl Language: Dutch / Nederlands",
  "Code: or Language: Odia / ଓଡ଼ିଆ",
  "Code: otq Language: Querétaro Otomi / Hñähñu",
  "Code: pa Language: Punjabi / ਪੰਜਾਬੀ",
  "Code: pl Language: Polish / Polski",
  "Code: prs Language: Dari / دری",
  "Code: ps Language: Pashto / پښتو",
  "Code: pt Language: Portuguese (Brazil) / Português (Brasil)",
  "Code: pt-PT Language: Portuguese (Portugal) / Português (Portugal)",
  "Code: ro Language: Romanian / Română",
  "Code: ru Language: Russian / Русский",
  "Code: sk Language: Slovak / Slovenčina",
  "Code: sl Language: Slovenian / Slovenščina",
  "Code: sm Language: Samoan / Gagana Sāmoa",
  "Code: so Language: Somali / Soomaali",
  "Code: sq Language: Albanian / Shqip",
  "Code: sr-Cyrl Language: Serbian (Cyrillic) / Српски (ћирилица)",
  "Code: sr-Latn Language: Serbian (Latin) / Srpski (latinica)",
  "Code: sv Language: Swedish / Svenska",
  "Code: sw Language: Swahili / Kiswahili",
  "Code: ta Language: Tamil / தமிழ்",
  "Code: te Language: Telugu / తెలుగు",
  "Code: th Language: Thai / ไทย",
  "Code: ti Language: Tigrinya / ትግር",
  "Code: tk Language: Turkmen / Türkmen Dili",
  "Code: tlh-Latn Language: Klingon (Latin) / Klingon (Latin)",
  "Code: tlh-Piqd Language: Klingon (pIqaD) / Klingon (pIqaD)",
  "Code: to Language: Tongan / Lea Fakatonga",
  "Code: tr Language: Turkish / Türkçe",
  "Code: tt Language: Tatar / Татар",
  "Code: ty Language: Tahitian / Reo Tahiti",
  "Code: ug Language: Uyghur / ئۇيغۇرچە",
  "Code: uk Language: Ukrainian / Українська",
  "Code: ur Language: Urdu / اردو",
  "Code: uz Language: Uzbek (Latin) / Uzbek (Latin)",
  "Code: vi Language: Vietnamese / Tiếng Việt",
  "Code: yua Language: Yucatec Maya / Yucatec Maya",
  "Code: yue Language: Cantonese (Traditional) / 粵語 (繁體)",
  "Code: zh-Hans Language: Chinese Simplified / 中文 (简体)",
  "Code: zh-Hant Language: Chinese Traditional / 繁體中文 (繁體)",
  "Code: zu Language: Zulu / Isi-Zulu",
];
